Linear Regression

In [24]:
from sklearn.datasets import fetch_openml
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [25]:

df = fetch_openml(name= "boston", version=1, as_frame=True)

# X = boston.data
# y = boston.target

# print(X.head())
# print(y.head())

dataset= pd.DataFrame(df.data)

In [26]:
dataset.columns = df.feature_names
dataset.head()

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296.0,15.3,396.90,4.98
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242.0,17.8,396.90,9.14
2,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242.0,17.8,392.83,4.03
3,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222.0,18.7,394.63,2.94
4,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222.0,18.7,396.90,5.33

In [27]:
# independent features and dependent features

X = dataset
y = df.target

y

0      24.0
1      21.6
2      34.7
3      33.4
4      36.2
       ...
501    22.4
502    20.6
503    23.9
504    22.0
505    11.9
Name: MEDV, Length: 506, dtype: float64

In [28]:
# train test split

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.31, random_state=34)

In [29]:
X_train

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT
32,1.38799,0.0,8.14,0,0.538,5.950,82.0,3.9900,4,307.0,21.0,232.60,27.71
210,0.17446,0.0,10.59,1,0.489,5.960,92.1,3.8771,4,277.0,18.6,393.25,17.27
438,13.67810,0.0,18.10,0,0.740,5.935,87.9,1.8206,24,666.0,20.2,68.95,34.02
278,0.07978,40.0,6.41,0,0.447,6.482,32.1,4.1403,4,254.0,17.6,396.90,7.19
223,0.61470,0.0,6.20,0,0.507,6.618,80.8,3.2721,8,307.0,17.4,396.90,7.60
...,...,...,...,...,...,...,...,...,...,...,...,...,...
246,0.33983,22.0,5.86,0,0.431,6.108,34.9,8.0555,7,330.0,19.1,390.18,9.16
361,3.83684,0.0,18.10,0,0.770,6.251,91.1,2.2955,24,666.0,20.2,350.65,14.19
490,0.20746,0.0,27.74,0,0.609,5.093,98.0,1.8226,4,711.0,20.1,318.43,29.68
122,0.09299,0.0,25.65,0,0.581,5.961,92.9,2.0869,2,188.0,19.1,378.09,17.93
417,25.94060,0.0,18.10,0,0.679,5.304,89.1,1.6475,24,666.0,20.2,127.36,26.64

In [30]:
# Linear regression
# standardizing the dataset

from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

In [ ]:
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test )

In [33]:
X_train

array([[-0.26709601, -0.49169581, -0.43744512, ...,  1.18253789,
        -1.31423076,  2.10133274],
       [-0.40892911, -0.49169581, -0.07662453, ...,  0.05825442,
         0.40929707,  0.65751548],
       [ 1.16932858, -0.49169581,  1.02940103, ...,  0.80777674,
        -3.06994398,  2.97398474],
       ...,
       [-0.40507218, -0.49169581,  2.44911959, ...,  0.76093159,
        -0.39340665,  2.37377718],
       [-0.41845103, -0.49169581,  2.14131754, ...,  0.29248014,
         0.24665355,  0.74879128],
       [ 2.6025262 , -0.49169581,  1.02940103, ...,  0.80777674,
        -2.44329437,  1.9533553 ]])

In [34]:
# inverse transform 

scaler.inverse_transform(X_train)

array([[1.38799e+00, 0.00000e+00, 8.14000e+00, ..., 2.10000e+01,
        2.32600e+02, 2.77100e+01],
       [1.74460e-01, 0.00000e+00, 1.05900e+01, ..., 1.86000e+01,
        3.93250e+02, 1.72700e+01],
       [1.36781e+01, 0.00000e+00, 1.81000e+01, ..., 2.02000e+01,
        6.89500e+01, 3.40200e+01],
       ...,
       [2.07460e-01, 0.00000e+00, 2.77400e+01, ..., 2.01000e+01,
        3.18430e+02, 2.96800e+01],
       [9.29900e-02, 0.00000e+00, 2.56500e+01, ..., 1.91000e+01,
        3.78090e+02, 1.79300e+01],
       [2.59406e+01, 0.00000e+00, 1.81000e+01, ..., 2.02000e+01,
        1.27360e+02, 2.66400e+01]])

In [35]:
from sklearn.linear_model import LinearRegression

# cross validation

from sklearn.model_selection import cross_val_score

In [ ]:
regression = LinearRegression()
cross_val_score(regression, X_train, Y_train, scoring= )